name: Workflow
on:
  push:
    branches: [main]
env:
  HEROKU_APP: previiiew
  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: nschloe/action-cached-lfs-checkout@v1
      - run: >
          heroku container:login &&
          heroku container:push web &&
          heroku container:release web
