name: Workflow
on:
  push:
    branches: [main]
env:
  HEROKU_APP: previiiew
  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: nschloe/action-cached-lfs-checkout@v1
      - run: rm .gitattributes
      - run: heroku container:login
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.heroku.com/${{env.HEROKU_APP}}/web
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: heroku container:release web
